---

- name: Empty repo directory
  file: path=/etc/yum.repos.d state=absent
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 6

- name: Mkdir empty repo directory
  file: path=/etc/yum.repos.d state=directory

- name: Copy repo file to remote server (rhel6.x)
  template: src=rhel68.j2 dest=/etc/yum.repos.d/rhel68.repo
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  
- name: Copy repo file to remote server (rhel7.x)
  template: src=rhel72.j2 dest=/etc/yum.repos.d/rhel72.repo
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 7

- name: Install python easy_install tools (via YUM)
  yum: name=python-setuptools state=latest
  when: ansible_pkg_mgr == "yum"

- name: Install python easy_install tools (via DNF)
  dnf: name=python-setuptools state=latest
  when: ansible_pkg_mgr == "dnf"

- name: Install python pip tools
  easy_install: name=pip state=latest

- name: Install pymongo package
  pip: name=pymongo state=latest
