---

- name: Fetch rhvm41 installer rpm
  get_url: url="{{ rhvm41rpm }}" dest=/tmp/rhvm41.rpm force=yes
  tags:
    - rhvm41up
    - fetch_latest_rpm

- name: Install the downloaded rpm
  command: rpm -ivh --force /tmp/rhvm41.rpm
  tags:
    - rhvm41up
    - fetch_latest_rpm

- name: get repo file path
  shell: rpm -qpl /tmp/rhvm41.rpm | grep -v release | grep -v dependencies
  register: rhvm41_repo
  tags:
    - rhvm41up

- name: fix a possbilbe bug in repo file
  lineinfile: dest="{{ rhvm41_repo.stdout }}" regexp='^(.*)\$releasever$' line='\g<1>7Server' backrefs=yes
  tags:
    - rhvm41up

- name: Copy answerbot to node
  copy: src="{{ role_path }}/bin/answerbot" dest=/tmp/answerbot  mode=0755
  tags:
    - rhvm41up

- name: Run engine-cleanup job
  command: /tmp/answerbot -e
  ignore_errors: True
  tags:
    - rhvm41up 

- name: Remove the old rhevm package
  yum: name=rhevm state=absent
  tags:
    - rhvm41up

- name: Install the new rhevm package
  yum: name=rhevm state=latest
  tags:
    - rhvm41up

- name: Update ovirt-engine-dwh-setup package
  yum: name=ovirt-engine-dwh-setup state=latest
  tags:
    - rhvm41up

- name: Run engine-setup job
  command: /tmp/answerbot -i
  tags:
    - rhvm41up
