---
- name: Upgrade rhevm to lastest version
  hosts: rhvm41

  roles:
    - roles/rhevm_upgrade/pre
    - { role: roles/rhevm_upgrade/mark_host_status, cmd: '{"$set":{"status":"upgrading"}}' }
    - roles/common/unregister_rhn_sm
    - roles/rhevm_upgrade/rhvm41
    - { role: roles/rhevm_upgrade/mark_host_status, cmd: '{"$set":{"status":"running"}}' }
